(() => {
"use strict";
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const state={score:0,streak:0,q:0,e:0,s:0,selected:null,sortScored:false};
const quiz=[
["My brother ___ coffee every morning.",["drink","drinks","is drinking"],"drinks","Every morning = routine → Present Simple."],
["She ___ coffee now.",["doesn't drink","isn't drinking","don't drink"],"isn't drinking","Now = Present Continuous negative."],
["___ you usually work from home?",["Do","Does","Are"],"Do","Use Do with you."],
["___ he play football on Sundays?",["Do","Does","Is"],"Does","Use Does with he."],
["Be quiet! The baby ___.",["sleeps","sleep","is sleeping"],"is sleeping","Be quiet! means it is happening now."],
["They ___ TV right now.",["aren't watching","don't watching","isn't watch"],"aren't watching","They + aren't + verb-ing."],
["___ she studying at the moment?",["Does","Is","Do"],"Is","Use Is + she + verb-ing."],
["We ___ English on Mondays.",["don't study","aren't study","doesn't study"],"don't study","We + don't + base verb."],
["Water ___ at 100°C.",["is boiling","boil","boils"],"boils","A general fact uses Present Simple."],
["Does Anna ___ English?",["speaks","speak","is speaking"],"speak","After Does use the base verb."],
["He ___ in London this week.",["doesn't live","isn't living","don't live"],"isn't living","This week = temporary situation."],
["I ___ for my exam at the moment.",["prepare","am preparing","prepares"],"am preparing","At the moment = Present Continuous."]
];
const errors=[["She don't like coffee.","She doesn't like coffee.","With she use doesn't."],["I am go to work every day.","I go to work every day.","Every day describes a routine."],["Are he working now?","Is he working now?","With he use Is."],["They doesn't watching TV.","They aren't watching TV.","They + aren't + verb-ing."],["Does she works here?","Does she work here?","After Does use the base verb."]];
const speed=[["I usually walk to work.","Present Simple","usually = regular habit"],["Look! The dog is running.","Present Continuous","Look! = happening now"],["We are staying here this week.","Present Continuous","this week = temporary"],["The Earth goes around the Sun.","Present Simple","general fact"],["Does Marta speak Spanish?","Present Simple","Does + base verb"],["Are they waiting for us?","Present Continuous","Are + verb-ing"]];
const markers=[["every morning","Present Simple"],["at the moment","Present Continuous"],["often","Present Simple"],["right now","Present Continuous"],["on Fridays","Present Simple"],["this month","Present Continuous"]];
function points(n=0){state.score+=n;$("#score").textContent=state.score;$("#streak").textContent=state.streak}function message(root,text,ok){const el=$(".feedback",root);if(el){el.textContent=text;el.style.color=ok?"#67e8a5":"#ff6b7d"}}
function renderQuiz(){const root=$("#activityQuiz"),q=quiz[state.q%quiz.length];root.innerHTML=`<div class="task-card"><div class="game-score">Quiz · ${state.q%quiz.length+1}/${quiz.length} · Score ${state.score}</div><div class="task-title">${q[0]}</div><div class="choice-grid">${q[1].map(x=>`<button type="button" class="choice" data-value="${x}">${x}</button>`).join("")}</div><p class="feedback"></p><button type="button" class="task-btn secondary" data-next>Next question</button></div>`;$$('.choice',root).forEach(b=>b.addEventListener('click',()=>{if($$('.choice:disabled',root).length)return;const ok=b.dataset.value===q[2];$$('.choice',root).forEach(x=>{x.disabled=true;if(x.dataset.value===q[2])x.classList.add('correct')});if(!ok)b.classList.add('wrong');if(ok){state.streak++;points(10+(state.streak-1)*2)}else{state.streak=0;points()}message(root,`${ok?'Correct.':'Not quite.'} ${q[3]}`,ok)}));$('[data-next]',root).addEventListener('click',()=>{state.q++;renderQuiz()})}
function clean(x){return x.trim().replace(/[.!?]$/,'').replace(/\s+/g,' ').toLowerCase()}function renderError(){const root=$("#activityError"),q=errors[state.e%errors.length];root.innerHTML=`<div class="task-card"><div class="game-score">Fix the mistake · ${state.e%errors.length+1}/${errors.length}</div><div class="task-title">Correct this sentence:</div><p class="example">${q[0]}</p><input class="task-input" placeholder="Type the corrected sentence"><div class="task-actions"><button type="button" class="task-btn" data-check>Check</button><button type="button" class="task-btn secondary" data-next>Next</button></div><p class="feedback"></p></div>`;$('[data-check]',root).addEventListener('click',()=>{const ok=clean($('.task-input',root).value)===clean(q[1]);if(ok)points(15);message(root,ok?`Excellent. ${q[2]}`:`Try again. Hint: ${q[2]}`,ok)});$('[data-next]',root).addEventListener('click',()=>{state.e++;renderError()})}
function renderSpeed(){const root=$("#activitySpeed"),q=speed[state.s%speed.length];root.innerHTML=`<div class="task-card"><div class="game-score">Simple or Continuous? · ${state.s%speed.length+1}/${speed.length}</div><div class="task-title">${q[0]}</div><div class="choice-grid"><button type="button" class="choice" data-value="Present Simple">Present Simple</button><button type="button" class="choice" data-value="Present Continuous">Present Continuous</button></div><p class="feedback"></p><button type="button" class="task-btn secondary" data-next>Next sentence</button></div>`;$$('.choice',root).forEach(b=>b.addEventListener('click',()=>{if($$('.choice:disabled',root).length)return;const ok=b.dataset.value===q[1];$$('.choice',root).forEach(x=>{x.disabled=true;if(x.dataset.value===q[1])x.classList.add('correct')});if(!ok)b.classList.add('wrong');if(ok)points(10);message(root,`${ok?'Correct.':'Not quite.'} ${q[2]}`,ok)}));$('[data-next]',root).addEventListener('click',()=>{state.s++;renderSpeed()})}
function renderSort(){state.selected=null;state.sortScored=false;const root=$("#activitySort"),items=[...markers].sort(()=>Math.random()-.5);root.innerHTML=`<div class="task-card"><div class="game-score">Sort the markers · click a card, then a column</div><div class="game-deck">${items.map((x,i)=>`<button type="button" draggable="true" class="game-card" data-type="${x[1]}" id="marker${i}">${x[0]}</button>`).join('')}</div><div class="game-columns"><button type="button" class="game-column" data-type="Present Simple"><h3>Present Simple</h3></button><button type="button" class="game-column" data-type="Present Continuous"><h3>Present Continuous</h3></button></div><p class="feedback"></p><button type="button" class="task-btn secondary" data-reset>New cards</button></div>`;$$('.game-card',root).forEach(c=>{c.addEventListener('click',()=>select(root,c));c.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',c.id))});$$('.game-column',root).forEach(col=>{col.addEventListener('dragover',e=>e.preventDefault());col.addEventListener('drop',e=>{e.preventDefault();const c=document.getElementById(e.dataTransfer.getData('text/plain'));if(c)place(root,c,col)});col.addEventListener('click',()=>{if(state.selected)place(root,state.selected,col)})});$('[data-reset]',root).addEventListener('click',renderSort)}function select(root,c){if(state.selected)state.selected.classList.remove('selected');state.selected=c;c.classList.add('selected');message(root,'Card selected. Now click a column.',true)}function place(root,c,col){col.appendChild(c);c.classList.remove('selected');state.selected=null;const placed=$$('.game-column .game-card',root);if(placed.length!==markers.length)return;const ok=placed.every(x=>x.dataset.type===x.parentElement.dataset.type);if(ok&&!state.sortScored){state.sortScored=true;points(30)}message(root,ok?'All markers are correct.':'Some markers are wrong. Move them and try again.',ok)}
function show(name){$$('.activity-view').forEach(x=>x.classList.add('hidden'));$(`#activity${name[0].toUpperCase()+name.slice(1)}`).classList.remove('hidden');({quiz:renderQuiz,error:renderError,speed:renderSpeed,sort:renderSort})[name]()}$$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#simpleRules').classList.toggle('hidden',t.dataset.tense!=='simple');$('#continuousRules').classList.toggle('hidden',t.dataset.tense!=='continuous')}));$$('.activity-tab').forEach(t=>t.addEventListener('click',()=>{$$('.activity-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');show(t.dataset.activity)}));points();show('quiz');
})();